name: Django tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: focave
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend
      - name: Run Tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: focave
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor
        run: |
          python manage.py test
        working-directory: backend